[application]
name = "EmberCastAI"
out_dir = "docs"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "EmberCastAI"

# Base path for Github Pages deployment
#base_path = "EmberCastAI"

[bundle]
identifier = "asf.alaska.edu"
publisher = "Alaska Satellite Facility"
icon = ["assets/icon.png"]
resouces = ["assets"]

